version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: dbt
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbt
    ports:
      - "5432:5432"
    volumes:
      - ./data:/sourcedata
      - ./temp:/temp
      # Copy the sql script to create and load tables
      - ./sql/create_and_load_tables.sql:/docker-entrypoint-initdb.d/create_and_load_tables.sql
